# Generated by Django 4.1.1 on 2023-01-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmit',
            name='status',
            field=models.CharField(default='Denied', max_length=20),
        ),
    ]
