# Generated by Django 4.1.1 on 2023-01-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_usersubmit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmit',
            name='jawaban',
            field=models.TextField(null=True),
        ),
    ]
