# Generated by Django 4.1.1 on 2023-01-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_usersubmit_jawaban'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmit',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubmit',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersubmit',
            name='status',
            field=models.CharField(default='Unsolved', max_length=20),
        ),
    ]
