# Generated by Django 4.1.1 on 2023-01-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_usersubmit_created_usersubmit_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubmit',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usersubmit',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
