# Generated by Django 4.1.1 on 2023-01-21 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_usersubmit_created_alter_usersubmit_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubmit',
            name='created',
        ),
        migrations.RemoveField(
            model_name='usersubmit',
            name='updated',
        ),
    ]
