# Generated by Django 4.1.1 on 2023-01-21 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_remove_usersubmit_created_remove_usersubmit_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmit',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubmit',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
