# Generated by Django 4.1.1 on 2023-01-17 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_soal_category_alter_soal_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='soal',
            name='code',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='soal',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
