# Generated by Django 4.1.1 on 2023-01-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_soal_code_alter_soal_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='soal',
            name='contoh',
            field=models.ImageField(null=True, upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='soal',
            name='course',
            field=models.CharField(choices=[('Java', 'Java'), ('HTML', 'HTML'), ('Kotlin', 'Kotlin'), ('PHP', 'PHP'), ('Android', 'Android')], max_length=20),
        ),
    ]
