# Generated by Django 4.1.1 on 2023-01-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_soal_contoh_alter_soal_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soal',
            name='contoh',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/'),
        ),
    ]
